# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0002_add_mptt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
    ]
